version: '2'
services:
    registry:
        restart: always
        image: registry:2
        ports:
            - "5000:5000"
        environment:
            REGISTRY_HTTP_TLS_CERTIFICATE: /certs/${certpath}/${certname}
            REGISTRY_HTTP_TLS_KEY: /certs/${certpath}/${keyname}
        volumes:
            - ${registryvolume}:/var/lib/registry
            - ${certsvolume}:/certs
   
