version: '2'
services:
    nginx:
        image: nginx
        ports:
            - "8081:8081 "
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ${certvolume}:/certs
        links:
            - artifactory
    artifactory:
        image: docker.bintray.io/jfrog/artifactory-pro:latest
        stdin_open: true
        tty: true
        labels:
            io.rancher.container.pull_image: always
        volumes:
            - afstore:/var/opt/jfrog/artifactory

volumes:
    afstore:
        driver: rancher-ebs
        driver_opts:
            name: artifactory
            size: 100
