.catalog:
  name: "Artifactory"
  version: "v1.2"
  description: "Artifactory build stack"
  uuid: artifactory-stack-2
  questions:
    - variable: "certvolume"
      description: "The name of the volume containing the certificates"
      label: "Certificate Volume:"
      required: true
      default: ""
      type: "string"
version: '2'
services:
  artifactory:
    scale: 1
    start_on_create: true
  nginx:
    scale: 1
    start_on_create: true
  pub:
    scale: 1
    start_on_create: true
    lb_config:
      certs:
        - "artifactory-certificates"
      port_rules:
      - priority: 1
        protocol: https
        service: nginx
        source_port: 8081
        target_port: 8081
      health_check:
        response_timeout: 2000
        healthy_threshold: 2
        port: 42
        unhealthy_threshold: 3
        interval: 2000
