version: '2'
services:
    web:
        image: nginx
        ports:
            - "80:80"
        volumes:
            - /usr/share/nginx/html
            - ${volume}:/etc/letsencrypt/
        labels:
            io.rancher.sidekicks: letsencrypt
    
    letsencrypt:
        image: quay.io/letsencrypt/letsencrypt
        volumes_from:
            - web
        command: certonly --agree-tos --webroot --webroot-path /usr/share/nginx/html -m certs@acmeticketing.com -d ${domains}
        labels:
            io.rancher.container.start_once=true
