version: '2'
services:
    web:
        image: nginx
        ports:
            - "80:80"
        volumes:
            - ${volume}:/usr/share/nginx/html
    
    ssl:
        image: quay.io/letsencrypt/letsencrypt
        volumes_from:
            - web
        command: certonly --agree-tos --webroot --webroot-path /usr/share/nginx/html -m certs@acmeticketing.com -d ${domains}

