version: '2'
services:
    loadbalancer:
        image: rancher/lb-service-haproxy:v0.6.4
        ports:
            - ${artifactory_port}:${artifactory_port}
    artifactory:
        image: docker.bintray.io/jfrog/artifactory-oss:latest
        stdin_open: true
        tty: true
        labels:
            io.rancher.container.pull_image: always
