.catalog:
  name: "ACME Build"
  version: "v1.0"
  description: "ACME build stack"
  uuid: acme-build-stack-0
  questions:
    - variable: "artifactory_port"
      description: "Artifactory port to expose"
      label: "Port:"
      required: true
      default: "8081"
      type: "int"
version: '2'
services:
    artifactory:
        scale: 1
        volumes:
            - afstore:/var/opt/jfrog/artifactory
    loadbalancer:
        scale: 1
        lb_config:
            port_rules:
                - protocol: http
                  service: artifactory
                  source_port: ${artifactory_port}
                  target_port: 8081
        health_check:
            port: 42
            interval: 2000
            unhealthy_threshold: 3
            healthy_threshold: 2
            response_timeout: 2000

volumes:
    afstore:
        driver: rancher-ebs
            driver_opts:
                size: 10
